spring:
  profiles:
    active: local

spring.batch.job.names: ${job.name:NONE}

---
spring:
  profiles: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
---
spring:
  profiles: mysql
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/spring_batch?useSSL=false
      username: freelife
      password: pass
      driver-class-name: com.mysql.cj.jdbc.Driver